version: "3.3"
# networks:
#   default:
#     external:
#       name: external-nextjs
services:
  pocdb:
    restart: always
    image: postgres:12.9
    ports:
      - "5472:5432"
    environment:
      - TZ=Europe/Istanbul
      - DEBUG=false
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pocdb
      - PGUSER=postgres
      - PG_TRUST_LOCALNET=true

    volumes:
      - /var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
